# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
 primary:
   <<: *default
   database: db/dev_multitenant_app.sqlite3

 primary_johndoe:
   <<: *default
   database: db/johndoe_dev_multitenant_app.sqlite3
   migrations_paths: db/tenants_migrations

 primary_timdoe:
   <<: *default
   database: db/timdoe_dev_multitenant_app.sqlite3
   migrations_paths: db/tenants_migrations

production:
  <<: *default
  database: db/production.sqlite3
